.\"                                      Hey, EMACS: -*- nroff -*-
.TH LIQ-CONTRIB 1 "November 26, 2008" "Liq-contrib"


.SH NAME
liq-contrib \- contributed scripts for the liquidsoap audio streaming language
.\"
.SH OVERVIEW
Contributed scripts are actually the following:
.TP
.B liq123 
Command line audio player that can use any output or format 
recongnized by liquidsoap. It may also submit to your lastfm account.
.TP
.B simpleliq 
This script helps you to create a simple script for streaming using 
liquidsoap. It can use various input, sound effects, track transisions, 
and outputs. You may print the resulting script and/or execute the result locally.
.TP
.B streamliqueur
Stream ripper using liquidsoap.
.TP
You can get more details on each program by trying \fBprogram \-\-help\fP.
.\"
.SH SEE ALSO
Our website
.B http://savonet.sf.net/
.\"
.SH AUTHOR
Romain Beauxis for Savonet <savonet-users@lists.sourceforge.net>


