# OCaml-Smbclient examples.
#
# Copyright (c) 2003 by the Savonet team.
#
# $Id$

all:
	$(MAKE) -f Makefile.osmbget

clean:
	-$(MAKE) -f Makefile.osmbget clean

distclean: clean
	rm -f config.log config.status Makefile.osmbget
