# OCaml-Fetch examples.
#
# Copyright 2003 by the Savonet team.
#
# $Id$

all:
	$(MAKE) -f Makefile.ufetch

opt:
	$(MAKE) -f Makefile.ufetch opt

install:
	$(MAKE) -f Makefile.ufetch install

clean:
	$(MAKE) -f Makefile.ufetch clean

distclean: clean
	rm -rf autom4te.cache config.log config.status
	rm -f Makefile.ufetch
