.\"                                      Hey, EMACS: -*- nroff -*-


.TH UFETCH 1 "February 28, 2004"


.SH NAME
ufetch \- download and upload files through various protocols such as ftp, samba or local files.


.SH SYNOPSIS
.B ufetch
.RI [ options ] " file " [ files ] " dest


.SH DESCRIPTION
This program does not do much (yet) and may even crash.


.SH OPTIONS
.TP
.B \-help, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.


.SH SEE ALSO
.BR wget (1),
.BR smbget (1).


.SH AUTHOR
This manual page was written by Samuel Mimram <samuel.mimram@ens-lyon.org>.
