liquidsoap-64.png: liquidsoap.svg
	inkscape $< -e $@ -w 64

liquidsoap-256.png: liquidsoap.svg
	inkscape $< -e $@ -w 256

liquidsoap-1024.png: liquidsoap.svg
	inkscape $< -e $@ -w 1024

liquidsoap-bubble-64.png: liquidsoap-bubble.svg
	inkscape $< -e $@ -w 64

liquidsoap-bubble-256.png: liquidsoap-bubble.svg
	inkscape $< -e $@ -w 256

liquidsoap-bubble-1024.png: liquidsoap-bubble.svg
	inkscape $< -e $@ -w 1024

